apiVersion: apps/v1
kind: Deployment
metadata:
  # O nome deployment. É o que você usa no comando `kubectl rollout restart`.
  name: hello
spec:
  # Alta disponibilidade com 2 cópias da aplicação.
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        # A pipeline de CI/CD vai substituir esta linha pela imagem correta e com a tag única.
        image: SUBTITUIDO_PELA_PIPELINE
        # Garante que o Kubernetes sempre tente baixar a imagem mais recente do repositório.
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # Define os recursos que o contêiner precisa e pode usar.
        # Essencial para o HPA funcionar e para a estabilidade do cluster.
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"

        # MONITORIA (Disponibilidade): Verifica se a aplicação está pronta para receber tráfego.
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10

        # MONITORIA (Disponibilidade): Verifica se a aplicação ainda está "viva" e a reinicia se falhar.
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10

        # Permite que os pods sejam agendados em nós spot (preemptivos).

        tolerations:
      - key: spot
        operator: Equal
        value: true
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello
spec:
  type: LoadBalancer # Cria um AWS Load Balancer
  selector:
    app: hello # Este Service vai direcionar tráfego para pods com a label "app: hello"
  ports:
  - protocol: TCP
    port: 80 # Porta que o Load Balancer VAI OUVIR (acesso externo)
    targetPort: 8080 # Porta que o Load Balancer VAI ENVIAR o tráfego para o CONTAINER
