# kubernetes/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-hpa
spec:
  # o deployment que será escalado
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello # O nome do deployment
  # Regras de escalabilidade

  minReplicas: 3 # Mínimo de 3 pods
  maxReplicas: 6 # Máximo de 6 pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # Gatilho: se a média de uso de CPU dos pods passar de 50%...
        averageUtilization: 50
