# imagem python
FROM python:3.9-slim-buster

# Definindo o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiando o arquivo de dependências
COPY requirements.txt ./

# Instalando as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copiando todo o resto da aplicação
COPY app.py ./

# SEGURANÇA: Criando e mudando para um usuário não-root
RUN useradd --create-home appuser
USER appuser

# Comando para executar a aplicação
CMD [ "python", "app.py" ]