# .github/workflows/cd.yml
name: CD - Deploy da Aplicação HelloWorld no EKS

on:
  push:
    # a 'trigger' será o push na main
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: hello
  EKS_CLUSTER_NAME: cluster-desafio-luizalabs-v2

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configura credenciais AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::288761731142:role/github-desafio-role #Arn da role criada no desafio
        aws-region: us-east-1 #Região onde está o EKS e ECR
              
    - name: Login no Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag e push da imagem Docker
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./app
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image_uri=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
        
    - name: Configura kubectl para o EKS
      run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
       
    - name: Deploy no Kubernetes
      env:
        IMAGE_URI: ${{ steps.build-image.outputs.image_uri }}
        KUBE_MANIFEST_PATH: ./k8s
        DEPLOYMENT_NAME: hello
      run: |
        #Passo 1: Usando 'sed' para atualizar o template apenas no deployment.yaml
        sed -i "s|image:.*|image: $IMAGE_URI|g" $KUBE_MANIFEST_PATH/deployment.yaml
        
        # Passo 2: Aplica apenas os arquivos da aplicação principal, um por um
        kubectl apply -f $KUBE_MANIFEST_PATH/deployment.yaml
        kubectl apply -f $KUBE_MANIFEST_PATH/service.yaml
        kubectl apply -f $KUBE_MANIFEST_PATH/hpa.yaml
        # --------------------
        
        echo "Aguardando o rollout da nova versão ser concluído..."
        # Passo 3: Verifica o status do deploy específico que foi alterado
        kubectl rollout status deployment/$DEPLOYMENT_NAME










