# .github/workflows/infra.yml
name: CI/CD - Infraestrutura com Terraform

on:
  push:
    branches: [ main ]
    paths: [ 'infra/**' ]
  pull_request:
    paths: [ 'infra/**' ]

env:
  TF_WORKING_DIR: ./infra

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configura credenciais AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::288761731142:role/github-desafio-role
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

    - name: Terraform Plan
      run: terraform -chdir=${{ env.TF_WORKING_DIR }} plan -out=tfplan

    # --- INÍCIO DA MELHORIA ---
    - name: Upload do Artefato do Plano
      # Salva o arquivo 'tfplan' para ser usado mais tarde
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: ${{ env.TF_WORKING_DIR }}/tfplan
    # --- FIM DA MELHORIA ---

    - name: Terraform Apply
      # Roda 'apply' APENAS em push para a branch 'main'
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # O apply agora executa o plano exato que foi gerado e salvo.
        terraform -chdir=${{ env.TF_WORKING_DIR }} apply -auto-approve tfplan